gestion/urls.py
from django.urls import path
from .views import register, EmailLoginView, EmailLogoutView, authenticated, home, order_details, order_status, \
    take_order, delete_order

app_name = 'gestion'

urlpatterns = [
    path('', home, name='home'),
    path('login/', EmailLoginView.as_view(), name='login'),
    path('logout/', EmailLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('authenticated/', authenticated, name='authenticated'),
    path('detail/<int:pedido_id>', order_details, name='detail'),
    path('status/<int:pedido_id>', order_status, name='status'),
    path('order/', take_order, name='order'),
    path('delete/<int:pedido_id>', delete_order, name='delete'),
]

telovendostore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion.urls'))
]

gestion/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
import base64

# import el manager que me permitira la creacion de usuarios y super usuarios
from .managers import CustomEmailUserManager


# Create your models here.
class CustomEmailUser(AbstractUser):
    # desabilito el campo username
    username = None
    # agrego el campos email como unico y sera el pricipal
    email = models.EmailField(_('correo electronico'), unique=True)
    rut = models.CharField(max_length=12, unique=True)
    nombre_completo = models.CharField(max_length=255)

    # coloco email como identificador unico
    USERNAME_FIELD = 'email'
    # campos que se pueden definir como requerido pero como tengo el email solo
    # colocare ese
    REQUIRED_FIELDS = []

    # especifico que todos lo modelos provienen de mi manager CustomEmailUserManager
    objects = CustomEmailUserManager()

    # mostrar el nombre del campo email, como correo electronico con el metodo str
    # que pasa un queryset a string
    def __str__(self):
        return self.email


# Modelo de productos
class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.BinaryField(null=True, blank=True)

    def imagen_base64(self):
        if self.imagen:
            return base64.b64encode(self.imagen).decode('utf-8')
        else:
            return None

    def __str__(self):
        return self.nombre


# Modelo de pedidos
class Pedido(models.Model):
    cliente = models.ForeignKey(CustomEmailUser, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, default=1)
    fecha = models.DateTimeField(auto_now_add=True)
    numero_pedido = models.AutoField(primary_key=True)
    estado = models.CharField(
        max_length=20,
        choices=[
            ("pendiente", "Pendiente"),
            ("preparacion", "En Preparación"),
            ("despacho", "En Despacho"),
            ("entregado", "Entregado"),
        ], default='pendiente'
    )
    direccion_entrega = models.TextField()
    forma_pago = models.CharField(max_length=50, choices=[
        ("debito", "Debito"),
        ("credito", "Credito"),
    ],
                                  )

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            DetallePedido.objects.create(pedido=self, producto=self.producto, cantidad=1,
                                         precio_unitario=self.producto.precio)

    def __str__(self):
        return f"Pedido #{self.numero_pedido}"


# Modelo de detalle de pedidos
class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.cantidad} x {self.producto} (Pedido #{self.pedido.numero_pedido})"

gestion/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm, ModelChoiceField
from django import forms
from .models import CustomEmailUser, Pedido, DetallePedido, Producto


# definicion de formularios para creacion de usuarios y modificacion de estos
# usando los predefinidos que Django provee
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomEmailUser
        fields = ('email', 'rut', 'nombre_completo')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomEmailUser
        fields = ('email', 'rut', 'nombre_completo')


class PedidoForm(ModelForm):
    class Meta:
        model = Pedido
        fields = '__all__'


class DetallePedidoForm(ModelForm):
    class Meta:
        model = DetallePedido
        fields = '__all__'


class ChangeStatusForm(ModelForm):
    class Meta:
        model = Pedido
        fields = ['estado']


class TakeOrderForm(ModelForm):
    cliente = ModelChoiceField(queryset=CustomEmailUser.objects.all())

    class Meta:
        model = Pedido
        fields = ['cliente', 'numero_pedido', 'direccion_entrega', 'forma_pago', 'producto']


class ProductoForm(forms.ModelForm):
    imagen_file = forms.FileField(required=False)

    class Meta:
        model = Producto
        exclude = ('imagen',)

    def save(self, commit=True):
        producto = super().save(commit=False)
        imagen_file = self.cleaned_data.get('imagen_file')

        if imagen_file:
            with imagen_file.open('rb') as file:
                producto.imagen = file.read()

        if commit:
            producto.save()

        return producto

gestion/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from django.utils.crypto import get_random_string
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import HiddenInput

from .forms import CustomUserCreationForm, ChangeStatusForm, TakeOrderForm
from .models import Pedido, DetallePedido, CustomEmailUser


# Create your views here.
def home(request):
    return render(request, template_name='gestion/home.html')


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        # genero una copia del formulario, ya que es inmutable por eso utilizo copy()
        form.data = form.data.copy()
        # accedo a los campos password 1 y 2 y les asigno una temporal para poder pasar la validacion
        # del form.is_valid()
        form.data['password1'] = settings.PASSWORD_TEMPORAL
        form.data['password2'] = settings.PASSWORD_TEMPORAL
        if form.is_valid():
            user = form.save(commit=False)
            temp_password = get_random_string(8)
            user.set_password(temp_password)
            user.save()
            send_mail(
                'Tu contraseña Temporal - Te Lo vendo',
                f'Hola {user.email}, aqui está tu contraseña temporal: {temp_password}\n Por favor cambia esta contraseña tras iniciar sesión por primera vez',
                'no-contestar@mailtrap.io',
                [user.email],
                fail_silently=False
            )
            return redirect('gestion:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'gestion/register.html', {'form': form})


class EmailLoginView(LoginView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('gestion:authenticated')
    template_name = 'gestion/login.html'


class EmailLogoutView(LogoutView):
    template_name = 'gestion/logout.html'
    next_page = 'gestion:logout'


@login_required(login_url='gestion:login')
def authenticated(request):
    if request.user.is_superuser or request.user.is_staff:
        pedidos_view = Pedido.objects.all()
        if pedidos_view.exists():
            return render(request, 'gestion/authenticated.html', context={'pedidos': pedidos_view})
        else:
            message = "No hay elementos que mostrar"
            return render(request, 'gestion/authenticated.html', context={'message': message})
    else:
        pedidos_view = Pedido.objects.filter(cliente_id=request.user.id)
        if pedidos_view.exists():
            return render(request, 'gestion/authenticated.html', context={'pedidos': pedidos_view})
        else:
            message = "No hay elementos que mostrar"
            return render(request, 'gestion/authenticated.html', context={'message': message})


@login_required(login_url='gestion:login')
def order_details(request, pedido_id):
    try:
        order_detail = DetallePedido.objects.get(pedido_id=pedido_id)
        return render(request, template_name='gestion/detail.html', context={'order_detail': order_detail})
    except DetallePedido.DoesNotExist:
        message = "No existe detalle del pedido"
        return render(request, 'gestion/detail.html', context={'message': message})


def order_status(request, pedido_id):
    order_details = get_object_or_404(Pedido, numero_pedido=pedido_id)
    if request.method == 'POST':
        change_status_form = ChangeStatusForm(request.POST, instance=order_details)
        if change_status_form.is_valid():
            change_status_form.save()
            send_mail(
                'Estado de envio - Te Lo vendo',
                f'Hola {order_details.cliente.nombre_completo}, su pedido a cambio de estado a {order_details.estado}',
                'no-contestar@mailtrap.io',
                [order_details.cliente.email],
                fail_silently=False
            )
            messages.success(request, "Estado del pedido cambiado correctamente.")
            return redirect('gestion:detail', pedido_id)
        else:
            messages.error(request, "No se ha podido guardar el estado")
    else:
        change_status_form = ChangeStatusForm(instance=order_details)

    return render(request, 'gestion/status.html', {'change_status_form': change_status_form})


def take_order(request):
    if request.method == 'POST':
        take_order_form = TakeOrderForm(request.POST)
        if take_order_form.is_valid():
            order = take_order_form.save(commit=False)
            if not request.user.is_superuser and not request.user.is_staff:
                order.cliente = request.user
            order.save()
            messages.success(request, "Pedido generado con éxito")
            return redirect('gestion:authenticated')
        else:
            messages.error(request, take_order_form.errors)
    else:
        take_order_form = TakeOrderForm(
            initial={'cliente': request.user if not request.user.is_superuser and not request.user.is_staff else None})

    return render(request, 'gestion/order.html', {
        'take_order_form': take_order_form,
        'is_superuser_or_staff': request.user.is_superuser or request.user.is_staff
    })


def delete_order(request, pedido_id):
    order = get_object_or_404(Pedido, numero_pedido=pedido_id)
    order.delete()
    messages.success(request, "Pedido eliminado correctamente.")
    return redirect('gestion:authenticated')

gestion/templates/gestion/authenticated.html
{% extends 'gestion/base.html' %}
{% block logout %}
    <div class="d-flex">
        <a class="btn btn-outline-secondary btn-sm me-2">Gestion de productos</a>
        <form method="post" action="{% url 'gestion:logout' %}">
            {% csrf_token %}
            <button class="btn btn-outline-danger btn-sm">Cerrar sesión</button>
        </form>
    </div>
{% endblock %}
{% block content %}
    <div class="container mt-4">
        <h4 class="text-center mb-3">Listado de Pedidos</h4>
        <div class="d-flex justify-content-end">
            <a href="{% url 'gestion:order' %}" class="btn btn-warning btn-sm mb-2">Tomar pedido</a>
        </div>
        <table class="table table-striped table-hover">
            <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Cliente</th>
                <th scope="col">Fecha</th>
                <th scope="col">Número de Pedido</th>
                <th scope="col">Estado</th>
                <th scope="col">Dirección de Entrega</th>
                <th scope="col">Forma de Pago</th>
                <th scope="col">Acciones</th>
            </tr>
            </thead>
            <tbody>
            {% for pedido in pedidos %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ pedido.cliente }}</td>
                    <td>{{ pedido.fecha }}</td>
                    <td class="text-center">{{ pedido.numero_pedido }}</td>
                    <td>
                        <span class="badge rounded-pill p-2
                            {% if pedido.estado == 'pendiente' %} bg-warning
                            {% elif pedido.estado == 'preparacion' %} bg-info
                            {% elif pedido.estado == 'despacho' %} bg-primary
                            {% elif pedido.estado == 'entregado' %} bg-success
                            {% endif %}
                        ">
                            {{ pedido.estado }}
                        </span>
                    </td>
                    <td>{{ pedido.direccion_entrega }}</td>
                    <td>{{ pedido.forma_pago }}</td>
                    <td>
                        <div class="d-flex justify-content-center">
                            <a class="btn btn-sm btn-secondary me-2"
                               href="{% url 'gestion:detail' pedido.numero_pedido %}">Ver</a>
                            {% if pedido.estado == 'pendiente' or pedido.estado == 'preparacion' %}
                                <form method="post" action="{% url 'gestion:delete' pedido.numero_pedido %}">
                                    {% csrf_token %}
                                    <button class="btn btn-sm btn-secondary">Cancelar</button>
                                </form>
                            {% endif %}
                        </div>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

gestion/templates/gestion/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'gestion/css/style.css' %}">
    <title>Te lo vendo</title>
</head>
<body>
<nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'gestion/img/shop.svg' %}" alt="Logo" width="30" height="30"
                 class="d-inline-block align-text-top me-2">
            Te lo Vendo Store
        </a>
        {% block logout %}
        {% endblock %}
    </div>
</nav>
{% block content %}
{% endblock %}
<footer class="footer mt-auto py-3 bg-light fixed-bottom">
    <div class="container text-center">
        <span class="text-muted"><img class="me-1" src="{% static 'gestion/img/c-circle.svg' %}"
                                      alt="">Te lo vendo store</span>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

gestion/templates/gestion/detail.html
{% extends 'gestion/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container w-50 mt-5 bg-light rounded-4">
        <div class="row d-flex justify-content-between p-3">
            <div class="col-2">
                <a class="btn btn-secondary btn-block btn-sm" href="{% url 'gestion:authenticated' %}">Volver</a>
            </div>
            <div class="col-6 text-end">
                {% if request.user.is_superuser or request.user.is_staff %}
                    <a class="btn btn-secondary btn-sm"
                       href="{% url 'gestion:status' order_detail.pedido.numero_pedido %}">Cambiar
                        Estado
                        Pedido</a>
                {% endif %}
            </div>
        </div>
        <div class="p-3">
            <h3 class="text-center">Detalle de Pedido</h3>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Cliente</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default"
                       value="{{ order_detail.pedido.cliente.nombre_completo }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-1">N° Pedido</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default"
                       value="{{ order_detail.pedido.numero_pedido }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Fecha compra</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default"
                       value="{{ order_detail.pedido.fecha| date }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Importe pagado</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default"
                       value="{{ order_detail.pedido.forma_pago }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Importe pagado</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default"
                       value="{{ order_detail.producto.precio }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Productos</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default"
                       value="{{ order_detail.producto.nombre }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-2">Estado Pedido</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default" value="{{ order_detail.pedido.estado }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-3">Dirección envio</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default" value="{{ order_detail.pedido.direccion_entrega }}"
                       disabled>
            </div>
            {% if order_detail.producto.imagen %}
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Imagen Producto</span>
                    <div class="form-control text-center">
                        <img class="w-50" src="data:image/jpeg;base64,{{ order_detail.producto.imagen_base64 }}"
                             alt="Imagen del producto">
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

gestion/templates/gestion/home.html
{% extends 'gestion/base.html' %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="card w-50 mb-3">
            <div class="card-body">
                <h5 class="card-title text-center mb-3">Bienvenidos a Te lo vendo store</h5>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'gestion:login' %}" class="btn btn-secondary btn-sm ">Ir a inicio de sesión</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gestion/templates/gestion/login.html
{% extends 'gestion/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5 ">
        <div class="row justify-content-center">
            <div class="col-md-4 bg-light rounded-3">
                <h3 class="text-center mb-4 mt-3">Inicio de sesión</h3>
                <form method="post">
                    {% csrf_token %}
                    <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}</label>
                    {{ form.username|attr:'class:form-control' }}
                    <label for="form.password.id_for_label"
                           class="form-label mt-2">{{ form.password.label }}</label>
                    {{ form.password|attr:'class:form-control mb-4' }}
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-secondary mb-4">Iniciar sesión</button>
                    </div>
                </form>
                <div class="d-flex justify-content-center mb-3">
                     <span>No estas registrado, <a
                             href="{% url 'gestion:register' %}">Registrate aca</a></span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gestion/templates/gestion/logout.html
{% extends 'gestion/base.html' %}
{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-4">
                <h3 class="mt-4 mb-3 text-center">Sesión cerrada con éxito</h3>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'gestion:home' %}" class="btn btn-secondary mt-3">Volver al Inicio</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gestion/templates/gestion/order.html
{% extends 'gestion/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container w-50 mt-5 bg-light rounded-4">
        <form method="post">
            {% csrf_token %}
            <div class="row d-flex justify-content-between p-3">

                <div class="col-2">
                    <a class="btn btn-secondary btn-block btn-sm" href="{% url 'gestion:authenticated' %}">Volver</a>
                </div>

                <div class="col-6 text-end">
                    <button class="btn btn-secondary btn-sm" type="submit">Crear pedido</button>
                </div>
            </div>
            <div class="p-3">
                <h3 class="text-center">Crear Pedido</h3>
                {% if is_superuser_or_staff %}
                    <div class="input-group mb-3 mt-3">
                        <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Cliente</span>
                        {% render_field take_order_form.cliente class='form-select' %}
                    </div>
                {% else %}
                    <div class="input-group mb-3 mt-3">
                        <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Cliente</span>
                        <input type="text" class="form-control" name="cliente" value="{{ request.user.email }}"
                               readonly>
                        <input type="hidden" name="cliente" value="{{ request.user.id }}">
                    </div>
                {% endif %}
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Producto</span>
                    {% render_field take_order_form.producto class='form-select' id='id_producto' %}
                </div>
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Dirección</span>
                    {% render_field take_order_form.direccion_entrega class='form-control' rows='2' %}
                </div>
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Forma de pago</span>
                    {% render_field take_order_form.forma_pago class='form-select' %}
                </div>
                {% if take_order_form.errors %}
                    <div class="alert alert-danger">
                        Por favor, corrige los siguientes errores:
                        <ul>
                            {% for field in take_order_form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

gestion/templates/gestion/register.html
{% extends 'gestion/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5 ">
        <div class="row justify-content-center">
            <div class="col-md-4 bg-light rounded-3">
                <h3 class="text-center mb-4 mt-3">Registro Usuarios</h3>
                <form method="post">
                    {% csrf_token %}
                    <label for="{{ form.email.id_for_label }}" class="form-label">{{ form.email.label }}</label>
                    {{ form.email|attr:'class:form-control' }}
                    <label for="{{ form.rut.id_for_label }}" class="form-label mt-2">{{ form.rut.label }}</label>
                    {{ form.rut|attr:'class:form-control' }}
                    <label for="{{ form.nombre_completo.id_for_label }}"
                           class="form-label mt-2">{{ form.nombre_completo.label }}</label>
                    {{ form.nombre_completo|attr:'class:form-control' }}
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-secondary mb-4 mt-3">Registrarse</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

gestion/templates/gestion/status.html
{% extends 'gestion/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container w-50 mt-5 bg-light rounded-4">
        <div class="row d-flex justify-content-between p-3">
            <div class="col-2">
                <a class="btn btn-secondary btn-block btn-sm" href="">Volver</a>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="p-3">
                <h3 class="text-center">Detalle de Pedido</h3>
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Actualizar Estado</span>
                    {% render_field change_status_form.estado class="form-select" %}
                </div>
                <div class="text-end">
                    <button type="submit" class="btn btn-secondary btn-sm ">Guardar
                        Cambios
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}